[package]
name = "device_virtio_console"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
license = "BSD-3-Clause"
edition = "2021"

[features]
registered_events = ["devices/registered_events"]

[dependencies]
anyhow = { workspace = true }
argh = { workspace = true }
base = { workspace = true }
cfg-if = { workspace = true }
cros_async = { workspace = true }
cros_tracing = { workspace = true }
data_model = { workspace = true }
devices = { workspace = true }
futures = { version = "0.3", features = ["async-await", "std"], default-features = false }
hypervisor = { workspace = true }
libc = { workspace = true }
remain = { workspace = true }
serde = { workspace = true, features = [ "derive", "rc" ] }
snapshot = { workspace = true }
sync = { workspace = true }
tempfile = "3.1"
thiserror = { workspace = true }
virtio_sys = { workspace = true }
vm_memory = { workspace = true }
vmm_vhost = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
jail = { workspace = true }
minijail = "*"
