#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Runs tests for both x86 and aarch64.

time ./ci/builder --vm ./run_tests &&
    time ./ci/aarch64_builder --vm ./run_tests
