[package]
name = "cros_asyncv2"
version = "0.2.0"
edition = "2021"

[features]
uring = ["io-uring"]

[dependencies]
anyhow = "1"
async-task = "4"
data_model = { path = "../data_model" } # provided by ebuild
futures = { version = "0.3", default-features = false, features = ["alloc"] }
intrusive-collections = "0.9"
io-uring = { version = "0.5", optional = true, features = ["unstable"] }
memoffset = "0.6"
once_cell = "1.7"
slab = "0.4"
smallvec = { version = "1.6.1", default-features = false, features = ["union"] }
sync = { path = "../sync" } # provided by ebuild
thiserror = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = { version = "0.7", features = ["os-ext"] }
base = { path = "../../base" } # provided by ebuild

[dev-dependencies]
futures = { version = "*", features = ["executor"] }
futures-executor = { version = "0.3", features = ["thread-pool"] }
futures-util = "0.3"
tempfile = "3"
