[package]
name = "device_virtio_net"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
license = "BSD-3-Clause"
edition = "2021"

[features]
pci-hotplug = ["devices/pci-hotplug"]
slirp = ["net_util/slirp"]
slirp-ring-capture = []

[dependencies]
anyhow = { workspace = true }
argh = { workspace = true }
base = { workspace = true }
cfg-if = { workspace = true }
cros_async = { workspace = true }
cros_tracing = { workspace = true }
data_model = { workspace = true }
devices = { workspace = true }
hypervisor = { workspace = true }
libc = { workspace = true }
net_util = { workspace = true }
remain = { workspace = true }
resources = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_keyvalue = { workspace = true, features = ["argh_derive"] }
snapshot = { workspace = true }
sync = { workspace = true }
thiserror = { workspace = true }
virtio_sys = { workspace = true }
vm_control = { workspace = true }
vm_memory = { workspace = true }
vmm_vhost = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }

[dev-dependencies]
devices = { workspace = true, features = ["test-util"] }

[dependencies.futures]
version = "0.3"
features = ["async-await", "std"]
default-features = false

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
jail = { workspace = true }
minijail = "*"
net_sys = { workspace = true }
vhost = { workspace = true }

[target.'cfg(windows)'.dependencies]
proc_init = { workspace = true }
tube_transporter = { workspace = true }
