#!/bin/bash
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Example VM with a simple ubuntu guest OS but no UI, audio or networking.

set -e

SRC=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
mkdir -p "$SRC/images/simple" && cd "$_"

if ! [ -f rootfs ]; then
    # ANCHOR: build
    # Build a simple ubuntu image and create a user with no password.
    virt-builder ubuntu-20.04 \
        --run-command "useradd -m -g sudo -p '' $USER ; chage -d 0 $USER" \
        -o ./rootfs
    # ANCHOR_END: build

    # ANCHOR: kernel
    virt-builder --get-kernel ./rootfs -o .
    # ANCHOR_END: kernel
fi

# ANCHOR: run
# Run crosvm.
# The rootfs is an image of a partitioned hard drive, so we need to tell
# the kernel which partition to use (vda5 in case of ubuntu-20.04).
cargo run --no-default-features -- run \
    --rwdisk ./rootfs \
    --initrd ./initrd.img-* \
    -p "root=/dev/vda5" \
    ./vmlinuz-*
# ANCHOR_END: run
