#!/bin/bash
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Example VM with internet access and sshd

set -e

sudo mkdir -p /var/empty
SRC=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
mkdir -p "$SRC/images/network" && cd "$_"

if ! [ -f rootfs ]; then
    # ANCHOR: build
    builder_args=(
        # Create user with no password.
        --run-command "useradd -m -g sudo -p '' $USER ; chage -d 0 $USER"

        # Configure network via netplan config in 01-netcfg.yaml
        --hostname crosvm-test
        # $SRC=/path/to/crosvm
        --copy-in "$SRC/guest/01-netcfg.yaml:/etc/netplan/"

        # Install sshd and authorized key for the user.
        --install openssh-server
        # OPTIONAL: inject RSA public key as known key
        # --ssh-inject "$USER:file:$HOME/.ssh/id_rsa.pub"

        -o rootfs
    )
    virt-builder ubuntu-20.04 "${builder_args[@]}"
    # ANCHOR_END: build

    virt-builder --get-kernel ./rootfs -o .
fi

# ANCHOR: run
# Use the previously configured crosvm_tap device for networking.
cargo run -- run \
    --rwdisk ./rootfs \
    --initrd ./initrd.img-* \
    --net tap-name=crosvm_tap \
    -p "root=/dev/vda5" \
    ./vmlinuz-*
# ANCHOR_END: run
