#!/bin/bash
# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file

# We require the crosvm binary to build before running the integration tests.
# There is an RFC for cargo to allow for this kind of dependency:
# https://github.com/rust-lang/cargo/issues/9096
cargo build -p crosvm
cargo nextest run
