#!/usr/bin/env bash
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "WARNING!"
echo ""
echo "Do not submit changes to this repository directly. Please submit changes upstream"
echo "to https://chromium.googlesource.com/crosvm/crosvm"
echo ""
echo "Use './tools/cl upload' instead of repo upload to do so."
echo ""
echo "WARNING!"

exit 1
