#!/usr/bin/env bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# To build crosvm using cargo against libraries and crates provided by ChromeOS
# use this script to update path references in Cargo.toml.

CARGO_PATH=$(dirname "$0")/../../Cargo.toml

declare -A replacements=(
    ["libcras_stub"]="../../third_party/adhd/cras/client/libcras"
    ["system_api_stub"]="../../platform2/system_api"
    ["third_party/minijail"]="../../aosp/external/minijail"
)

for crate in "${!replacements[@]}"; do
    echo "Replacing '${crate}' with '${replacements[$crate]}'"
    sed -i "s|path = \"${crate}|path = \"${replacements[$crate]}|g" \
        "${CARGO_PATH}"
done

echo "Modified Cargo.toml with new paths. Please do not commit those."
