#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Simulates all kokoro jobs.

cd $(dirname "$0")
time ./simulate build-x86_64.sh &&
  time ./simulate build-aarch64.sh
