#!/bin/bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
crosvm_root=$(realpath "$(dirname $0)/..")
export CROSVM_BUILDER_SCRATCH_DIR="\
${crosvm_root}/target/ci/crosvm_aarch64_builder"

"$(dirname $0)/run_container.sh" crosvm_aarch64_builder "$@"
