#!/usr/bin/env bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -ex

# Note: This requires riscv64 packages to be available via apt, which can be obtained
# from the debian-ports repository.
sudo apt-get install --yes --no-install-recommends \
  binutils-riscv64-linux-gnu \
  g++-riscv64-linux-gnu \
  libcap-dev:riscv64 \
  libwayland-dev:riscv64 \
  qemu-user-static

# Add riscv64gc target to Rust
rustup target add riscv64gc-unknown-linux-gnu
