#!/usr/bin/env bash
# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -ex

sudo apt-get update
sudo apt-get install --yes --no-install-recommends \
    ca-certificates \
    cloud-image-utils \
    curl \
    dpkg-dev \
    expect \
    gcc \
    git \
    jq \
    libasound2-dev \
    libcap-dev \
    libclang-dev \
    libdbus-1-dev \
    libdrm-dev \
    libepoxy-dev \
    libssl-dev \
    libwayland-dev \
    libxext-dev \
    make \
    nasm \
    ninja-build \
    openssh-client \
    pkg-config \
    protobuf-compiler \
    python3 \
    python3-pip \
    python3-setuptools \
    qemu-system-x86 \
    rsync \
    screen \
    wine64 \
    gcc-mingw-w64-x86-64-win32 \
    wayland-protocols

# Install meson for rutabaga_gfx
pip3 install meson

# We use mdformat to keep the mdbook at docs/ formatted
pip3 install mdformat

# We use argh in our cli developer tools
pip3 install argh

rustup component add clippy
rustup component add rustfmt

rustup target add x86_64-pc-windows-gnu

# The bindgen tool is required to build a crosvm dependency.
cargo install bindgen

# The mdbook and mdbook-mermaid tools are used to build the crosvm book.
cargo install mdbook --no-default-features --version "^0.4.10"
cargo install mdbook-mermaid --version "^0.8.3"
cargo install mdbook-linkcheck --version "^0.7.6"
