#!/usr/bin/env bash
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -ex

cd $(dirname $0)/..

cargo build -p base --target=aarch64-apple-darwin
cargo clippy -p base --target=aarch64-apple-darwin
