#!/usr/bin/env bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -ex

$(dirname $0)/deps/install-mingw64-debs
$(dirname $0)/deps/install-mingw64-other
