#!/usr/bin/env python3
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
from impl.common import TOOLS_ROOT, cmd

if __name__ == "__main__":
    sys.exit(
        cmd(sys.executable, TOOLS_ROOT / "testvm", *sys.argv[1:], "--arch=x86_64").fg(check=False)
    )
