#!/usr/bin/env python3
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from impl.testvm import main
import sys

if __name__ == "__main__":
    main("x86_64", sys.argv[1:])
